name: Build Linux

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Libraries
        run: |
          sudo apt update
          sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-gfx-dev

      - name: Install AFK
        run: |
          git clone https://github.com/AdsGames/AfkLib
          cd AfkLib
          cmake .
          sudo make install -j4
          cd ../

      - name: Run CMake
        run: cmake .

      - name: Make
        run: make -j4
