name: Deploy Game

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Web
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: "./build/release/_deps"
          key: deps-${{ runner.os }}

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.6
          actions-cache-folder: "emsdk-cache"

      - name: Download ports
        run: |
          embuilder build harfbuzz

      - name: Configure
        run: emcmake cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(git describe --tags --always)" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/release/target/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deploy to A.D.S. Games
        if: startsWith(github.ref, 'refs/tags/v')
        uses: adsgames/deploy-to-adsgames@v1
        with:
          project-id: robotflier
          build-dir: ./build/release/target/
          platform: WEB
          bucket-access-key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
          bucket-secret-key: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}
          api-key: ${{ secrets.ADSGAMES_API_KEY }}

  deploy-binary:
    name: Deploy Binary
    strategy:
      matrix:
        platform:
          - system: windows-2022
            cpack_type: Windows
            release_type: WINDOWS
          - system: ubuntu-24.04
            cpack_type: Linux
            release_type: LINUX
          - system: macos-15
            cpack_type: Darwin
            release_type: MACOS

    runs-on: ${{ matrix.platform.system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: "./build/release/_deps"
          key: deps-binary-${{ runner.os }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(git describe --tags --always)" >> "$GITHUB_OUTPUT"

      - name: Install linux packages
        if: matrix.platform.system == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install --fix-missing -y \
            cmake make ninja-build libasound2-dev libpulse-dev \
            libaudio-dev libfribidi-dev libjack-dev libsndio-dev libusb-1.0-0-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libwayland-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libpipewire-0.3-dev libdecor-0-dev

      - name: Configure
        run: cmake --preset release -DPROJECT_VERSION="3.0.0"

      - name: Build and Package
        run: cmake --build --preset release --target package

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/release/RobotFlier-${{ matrix.platform.type }}-3.0.0.zip
          asset_name: RobotFlier-${{ matrix.platform.cpack_type }}-v3.0.0.zip
          asset_content_type: application/zip

      - name: Deploy to A.D.S. Games
        if: startsWith(github.ref, 'refs/tags/v')
        uses: adsgames/deploy-to-adsgames@v1
        with:
          project-id: robotflier
          build-dir: ./build/release/target/
          platform: ${{ matrix.platform.release_type }}
          bucket-access-key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
          bucket-secret-key: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}
          api-key: ${{ secrets.ADSGAMES_API_KEY }}
