name: Test Builds

on:
  push:
    branches: [ master, test-builds ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Libraries
      run: |
        sudo apt install liballegro5-dev liballegro-acodec5-dev liballegro-audio5-dev liballegro-image5-dev liballegro-dialog5-dev liballegro-ttf5-dev
        
    - name: Run CMake
      run: cmake -G "Unix Makefiles" .
      
    - name: Make
      run: make
  
  build-mac:
    name: Build Mac OS
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Libraries
      run: |
        brew install allegro
        
    - name: Run CMake
      run: cmake -G "Unix Makefiles" .
    
    - name: Make
      run: |
        export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/local/include"
        make
   
  build-windoze:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Libraries
      run: |
        $env:Path += ";C:\msys64\usr\bin;"
        pacman --noconfirm -S mingw-w64-i686-gcc-libs mingw-w64-i686-dumb mingw-w64-i686-flac mingw-w64-i686-opusfile mingw-w64-i686-freetype mingw-w64-i686-libjpeg-turbo mingw-w64-i686-libpng mingw-w64-i686-libvorbis mingw-w64-i686-libwebp mingw-w64-i686-openal mingw-w64-i686-physfs mingw-w64-i686-allegro
      
    - name: Run CMake
      run: |
        $env:Path += ";C:\msys64\mingw32\lib;"
        ls C:\msys64\mingw32\lib
        cmake -G "MSYS Makefiles" .
      
    - name: Make
      run: |
        $env:Path += ";C:\msys64\mingw32\include;"
        make
      
     
