name: Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Libraries
      run: |
        sudo apt install liballegro5-dev liballegro-acodec5-dev liballegro-audio5-dev liballegro-image5-dev liballegro-dialog5-dev liballegro-ttf5-dev
      
    - name: Install CMake
      run: |
        sudo apt install cmake
        
    - name: Run CMake
      run: cmake -G "Unix Makefiles"
      
    - name: Make
      run: make
      
